#!/bin/bash
set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

pip3 install --no-cache -e . 

rm -rf src
pip3 install -e git+https://github.com/singnet/reputation.git@folder-soft-refactor#egg=agency

popd  