#!/bin/bash
set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

python3 setup.py develop

rm -rf src
pip3 install -e git+https://github.com/singnet/reputation.git#egg=reputation

popd  
